---
name: go
on: [push]  # yamllint disable-line rule:truthy
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: run staticcheck
        run: staticcheck ./...
